insert into State(id, nome, uf) VALUES
                                     (null, 'Acre', 'AC'),
                                     (null, 'Alagoas', 'AL'),
                                     (null, 'Amazonas', 'AM'),
                                     (null, 'Amapá', 'AP'),
                                     (null, 'Bahia', 'BA'),
                                     (null, 'Ceará', 'CE'),
                                     (null, 'Distrito Federal'),
                                     (null, 'Espírito Santo'),
                                     (null, 'Goiás', 'GO'),
                                     (null, 'Maranhão'),
                                     (null, 'Minas Gerais'),
                                     (null, 'Mato Grosso do Sul'),
                                     (null, 'Mato Grosso', 'MT'),
                                     (null, 'Pará', 'PA'),
                                     (null, 'Paraíba', 'PB'),
                                     (null, 'Pernambuco', 'PE'),
                                     (null, 'Piauí', 'PI'),
                                     (null, 'Paraná', 'PR'),
                                     (null, 'Rio de Janeiro'),
                                     (null, 'Rio Grande do Norte'),
                                     (null, 'Rondônia', 'RO');